#!/bin/sh

### BEGIN INIT INFO
# Provides:        epics-LTC2983
# Required-Start:  $network $remote_fs $syslog ntp
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start EPICS IOC for LTC2983
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

dev_eth0_1=`/sbin/ifconfig eth0:1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
dev_eth0_2=`/sbin/ifconfig eth0:2 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`

case "$1" in
  start)
    echo -n "Starting LTC2983-ioc"
    export EPICS_HOST_ARCH=linux-arm
    export LD_LIBRARY_PATH=/opt/epics/base/lib/linux-arm

    export EPICS_CAS_INTF_ADDR_LIST=$dev_eth0_1
    export EPICS_CAS_SERVER_PORT="6064"
    cd /opt/LTC2983-ioc/iocBoot/iocLTC2983
    screen -d -m -S ioc /opt/LTC2983-ioc/bin/linux-arm/LTC2983 ioc-spi01.cmd

    export EPICS_CAS_INTF_ADDR_LIST=$dev_eth0_2
    export EPICS_CAS_SERVER_PORT="6064"
    screen -d -m -S ioc /opt/LTC2983-ioc/bin/linux-arm/LTC2983 ioc-spi02.cmd
    echo "."
    ;;
  stop)
    echo -n "Stopping LTC2983-ioc"
    kill -9 `/bin/pidof /opt/LTC2983-ioc/bin/linux-arm/LTC2983`
    unset EPICS_HOST_ARCH
    echo "."
    ;;
  force-reload|restart)
    sh $0 stop
    sh $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/epics-LTC2983 {start|stop|restart|force-reload}"
    exit 1
    ;;
esac
